DocWorks for editor-elements - 9 changes detected, but 3 issue detected changes: Service $w.Breadcrumbs property isEllipsisVisible has a new link [itemsAfterEllipsis](#itemsAfterEllipsis), [itemsBeforeEllipsis](#itemsBeforeEllipsis), [showEllipsis](#showEllipsis), [hideEllipsis](#hideEllipsis) Service $w.Breadcrumbs property isEllipsisVisible link [itemsAfterEllipsis](#itemsAfterEllipsis),[itemsBeforeEllipsis](#itemsBeforeEllipsis), [showEllipsis](#showEllipsis), [hideEllipsis](#hideEllipsis) was removed Service $w.Breadcrumbs property isEllipsisVisible.examples has 1 new examples Service $w.Breadcrumbs operation hideEllipsis has a new link [itemsAfterEllipsis](#itemsAfterEllipsis), [itemsBeforeEllipsis](#itemsBeforeEllipsis), [isEllipsisVisible](#isEllipsisVisible), [showEllipsis](#showEllipsis) Service $w.Breadcrumbs operation hideEllipsis link [itemsAfterEllipsis](#itemsAfterEllipsis),[itemsBeforeEllipsis](#itemsBeforeEllipsis), [isEllipsisVisible](#isEllipsisVisible), [showEllipsis](#showEllipsis) was removed Service $w.Breadcrumbs operation hideEllipsis.examples has 2 new examples Service $w.Breadcrumbs operation showEllipsis has a new link [itemsAfterEllipsis](#itemsAfterEllipsis), [itemsBeforeEllipsis](#itemsBeforeEllipsis), [isEllipsisVisible](#isEllipsisVisible), [hideEllipsis](#hideEllipsis) Service $w.Breadcrumbs operation showEllipsis link [itemsAfterEllipsis](#itemsAfterEllipsis),[itemsBeforeEllipsis](#itemsBeforeEllipsis), [isEllipsisVisible](#isEllipsisVisible), [hideEllipsis](#hideEllipsis) was removed Service $w.Breadcrumbs operation showEllipsis.examples has 2 new examples
issues:
Mixin $w.HiddenCollapsedMixin not found (Breadcrumbs.js (1))
Mixin $w.ViewportMixin not found (Breadcrumbs.js (1))
ERROR: The @snippet tag - file 'velo-docs/examples/Breadcrumbs-isEllipsisVsisibleScenario.es6' not found. File: Breadcrumbs.js line: 140