DocWorks for wix-crm-backend - 3 changes detected, but 5 issue detected changes: Service wix-crm-backend.Events message ContactMergedEvent member entity was removed Service wix-crm-backend.Events message ContactMergedEvent has a new member data Service wix-crm-backend.Events has a new message ContactMergedData
issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (94))
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/events/onContactMerged.es6' not found. File: events.js line: 190
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1